name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # icons
  cupertino_icons: ^1.0.2
  
  # get package and get_storage to save personal data
  get: ^4.3.8
  get_storage: ^2.0.3
  
  # package of navigation
  md2_tab_indicator: ^1.0.2
  dot_navigation_bar: ^0.1.1
  
  # fast implementation of splash screen
  splashscreen: ^1.2.0
  
  # package support svg files
  flutter_svg: ^0.19.0

  # datetime formater package
  intl: ^0.16.1

  # package support json animations
  lottie: ^0.7.0

  # google maps, permissions, http to select address with map
  # google_maps_flutter: ^1.0.6
  # geolocator: ^6.1.0
  # geocoding: ^1.0.5
  http: ^0.12.0+4
  # permission_handler: ^5.1.0
  # google_maps_place_picker: ^1.0.1

  # loader shimmer animation
  shimmer_animation: ^1.0.0

  # package to caching images
  cached_network_image: ^2.5.1

  # flutter stripe packages intregration
  # stripe_payment: ^1.0.11
  # stripe_payment:
  # modal_progress_hud: ^0.1.3

  # open app settings
  # app_settings: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  image_path: 'assets/icons/main_icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          # weight: 100
        - asset: assets/fonts/Poppins-Bold.ttf
          # weight: 500
    

  
